import '@/assets/styles/index.scss';
import { Providers } from './provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
    <body>
    <main>
      <Providers>
        {children}
      </Providers>
    </main>
    <div id='portal'></div>
    </body>
    </html>
  );
}
